### ISSUE TITLE
Gerar Mock com dados do DICT

### ISSUE THREAD

**Issue by KahCosta** [Vamos-Parcelar-Lift-Learning/Mock-Dict#2]
- [x] Utilizando a biblioteca Json Server, mockar os dados referentes as chaves possíveis de utilização como: CPF, CNPJ, EMAIL e TELEFONE, vinculados aos dados bancários do usuário
- [x] Criar schema referente aos dados bancários de forma dinâmica, vinculados a chave do DICT

Abaixo está especificado o Schema vínculo:

```
{
		“type”: “object”,
		“properties”: {
	“Account”: {
	“type”: “object”,
	“properties”: {
			“AccountNumber”: string
		“AccountType”: string
		“Branch”: string
		“OpeningDate”: string
		“Participant”: string
},
required: all
},
“key”: string,
“keyType”: “string”,
“Owner”:{
	“properties”: {
		“Name”: string
		“TaxIdNumber”: number
		“Type”: string
		“tradeName”: string
},
required: all
}
},
required: all
}
```

Para auxílio no desenvolvimento do mock, segue sugestão de documentação:
[Mock com Json Server](https://www.fabricadecodigo.com/json-server/)

**Comment by Matheus456** [comment]
Esta issue já foi solucionada no PR #5
